/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Util.ClassImages;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ItemEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.Collections;
import javax.swing.BorderFactory;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.FaceTexture;
import service.BackgroundService;
import service.FaceTextureService;

/**
 *
 * @author ghpm9
 */
public class FaceTextureFrame extends javax.swing.JInternalFrame {

    private FaceTextureService faceTextureService;
    private BackgroundService backgroundService;
    private BackgroundService newFaceTexture;
    private int indexFaceTexture = 0;
    private int x, y;

    /**
     * Creates new form FaceTextureFrame
     */
    public FaceTextureFrame(FaceTextureService faceTextureService, BackgroundService backgroundService) {
        this.faceTextureService = faceTextureService;
        this.backgroundService = backgroundService;
        this.newFaceTexture = new BackgroundService("images/vazio.png", 125, 160);
        initComponents();
        generateFaceTextureLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        faceTextureChooser = new javax.swing.JFileChooser();
        faceTextureInternalFrame = new javax.swing.JDialog();
        labelNewFaceTexture = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        facePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        classComboBox = new javax.swing.JComboBox<>();
        showClassCheckBox = new javax.swing.JCheckBox();
        nameFaceTexture = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        faceTextureChooser.setMultiSelectionEnabled(true);

        faceTextureInternalFrame.setTitle("Alterar Imagem");
        faceTextureInternalFrame.setMaximumSize(new java.awt.Dimension(225, 270));
        faceTextureInternalFrame.setMinimumSize(new java.awt.Dimension(225, 270));
        faceTextureInternalFrame.setModal(true);
        faceTextureInternalFrame.setName("Alterar Imagem"); // NOI18N
        faceTextureInternalFrame.setPreferredSize(new java.awt.Dimension(225, 270));
        faceTextureInternalFrame.setResizable(false);

        labelNewFaceTexture.setMaximumSize(new java.awt.Dimension(125, 160));
        labelNewFaceTexture.setMinimumSize(new java.awt.Dimension(125, 160));
        labelNewFaceTexture.setPreferredSize(new java.awt.Dimension(125, 160));
        labelNewFaceTexture.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                labelNewFaceTextureMouseDragged(evt);
            }
        });
        labelNewFaceTexture.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                labelNewFaceTextureMouseWheelMoved(evt);
            }
        });
        labelNewFaceTexture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelNewFaceTextureMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelNewFaceTextureMouseReleased(evt);
            }
        });

        jButton6.setText("Salvar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout faceTextureInternalFrameLayout = new javax.swing.GroupLayout(faceTextureInternalFrame.getContentPane());
        faceTextureInternalFrame.getContentPane().setLayout(faceTextureInternalFrameLayout);
        faceTextureInternalFrameLayout.setHorizontalGroup(
            faceTextureInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faceTextureInternalFrameLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(faceTextureInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNewFaceTexture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        faceTextureInternalFrameLayout.setVerticalGroup(
            faceTextureInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faceTextureInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNewFaceTexture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setTitle("FaceTexture");
        setPreferredSize(new java.awt.Dimension(1200, 770));

        facePanel.setLayout(new java.awt.GridLayout(0, 7, 5, 5));
        jScrollPane1.setViewportView(facePanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setMaximumSize(new java.awt.Dimension(930, 736));
        jPanel3.setMinimumSize(new java.awt.Dimension(930, 736));
        jPanel3.setOpaque(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setText("Arquivo Nome");

        jLabel3.setText("Class:");

        classComboBox.setModel(getClassBDO());
        classComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                classComboBoxItemStateChanged(evt);
            }
        });

        showClassCheckBox.setText("Show Class");
        showClassCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showClassCheckBoxItemStateChanged(evt);
            }
        });

        nameFaceTexture.setText("name");

        jButton2.setText("Alterar Imagem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Importar Face Textures");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Remover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mover");

        jButton4.setText("Anterior");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Avançar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nameFaceTexture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(showClassCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameFaceTexture))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showClassCheckBox)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 437, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showClassCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showClassCheckBoxItemStateChanged
        // TODO add your handling code here:
        faceTextureService.getFaceTexture(indexFaceTexture).setShowClasse(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_showClassCheckBoxItemStateChanged

    private void classComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_classComboBoxItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            faceTextureService.getFaceTexture(indexFaceTexture).setClasse((String) evt.getItem());
        }
    }//GEN-LAST:event_classComboBoxItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("BMP Images", "bmp");
        faceTextureChooser.setFileFilter(filter);
        int returnVal = faceTextureChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File[] files = faceTextureChooser.getSelectedFiles();
            for (File file : files) {
                FaceTexture newFaceTexture = new FaceTexture();
                newFaceTexture.setName(file.getName());
                newFaceTexture.setImage(file.getAbsolutePath());
                newFaceTexture.setClasse("Null");
                faceTextureService.addFaceTexture(newFaceTexture);
            }
        }
        generateFaceTextureLabel();
        updateChangeFaceTexture();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:  
        if (faceTextureService.getFaceTextures().size() > 1) {
            faceTextureService.getFaceTextures().remove(indexFaceTexture);
            generateFaceTextureLabel();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (indexFaceTexture > 0) {
            Collections.swap(faceTextureService.getFaceTextures(), indexFaceTexture, indexFaceTexture - 1);
            indexFaceTexture--;
            generateFaceTextureLabel();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (indexFaceTexture < (faceTextureService.getFaceTextures().size() - 1)) {
            Collections.swap(faceTextureService.getFaceTextures(), indexFaceTexture, indexFaceTexture + 1);
            indexFaceTexture++;
            generateFaceTextureLabel();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "bmp", "jpg", "jpeg", "png");
        File file = selectFile(filter);
        if (file != null && filter.accept(file)) {
            newFaceTexture.setImage(file.getAbsolutePath());
            updateNewFaceTextureLabel();
            faceTextureInternalFrame.setVisible(true);   
            
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void labelNewFaceTextureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNewFaceTextureMousePressed
        // TODO add your handling code here:
        evt.getComponent().setCursor(new Cursor(Cursor.MOVE_CURSOR));
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_labelNewFaceTextureMousePressed

    private void labelNewFaceTextureMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNewFaceTextureMouseReleased
        // TODO add your handling code here:
        evt.getComponent().setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_labelNewFaceTextureMouseReleased

    private void labelNewFaceTextureMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNewFaceTextureMouseDragged
        // TODO add your handling code here:
        int moveX = evt.getX() - x;
        int moveY = evt.getY() - y;
        x = evt.getX();
        y = evt.getY();

        newFaceTexture.moveX(moveX);
        newFaceTexture.moveY(moveY);

        updateNewFaceTextureLabel();
    }//GEN-LAST:event_labelNewFaceTextureMouseDragged

    private void labelNewFaceTextureMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_labelNewFaceTextureMouseWheelMoved
        // TODO add your handling code here:
        newFaceTexture.setZoom(evt.getPreciseWheelRotation());
        updateNewFaceTextureLabel();
    }//GEN-LAST:event_labelNewFaceTextureMouseWheelMoved

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        faceTextureService.getFaceTexture(indexFaceTexture).setImage(newFaceTexture.getBackground());
        faceTextureInternalFrame.setVisible(false);
        generateFaceTextureLabel();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void updateNewFaceTextureLabel() {
        labelNewFaceTexture.setIcon(getIconFromFaceTexture());
    }

    private Icon getIconFromFaceTexture() {
        ImageIcon icon = new ImageIcon(newFaceTexture.getBackground());

        return icon;
    }

    private void updateChangeFaceTexture() {

        FaceTexture faceTextureTemp = faceTextureService.getFaceTexture(indexFaceTexture);
        nameFaceTexture.setText(faceTextureTemp.getName());
        classComboBox.setSelectedItem(faceTextureTemp.getClasse());
        showClassCheckBox.setSelected(faceTextureTemp.isShowClasse());

    }

    private Icon getIconFromFaceTexture(int index) {
        ImageIcon icon = new ImageIcon(faceTextureService.getFaceTexture(index).getImage(125, 160));

        return icon;
    }

    private ComboBoxModel getClassBDO() {
        return new DefaultComboBoxModel(ClassImages.getAllClass());
    }

    private void setIndexFaceTexture(MouseEvent event, int index) {
        this.indexFaceTexture = index;
        //((JLabel) event.getComponent()).setBorder(BorderFactory.createLineBorder(Color.black));
        focusLabel((JLabel) event.getComponent());
        updateChangeFaceTexture();
        if (event.getClickCount() == 2 && event.getButton() == MouseEvent.BUTTON1) {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("BMP Images", "bmp");
            File file = selectFile(filter);
            if (file != null) {
                faceTextureService.getFaceTexture(indexFaceTexture).setName(file.getName());
                faceTextureService.getFaceTexture(indexFaceTexture).setImage(file.getAbsolutePath());
            }
            if (event.getComponent() instanceof JLabel) {
                JLabel label = (JLabel) event.getComponent();
                label.setIcon(getIconFromFaceTexture(indexFaceTexture));

            }
        }

    }

    private void focusLabel(JLabel focus) {
        for (Component component : facePanel.getComponents()) {
            if (component instanceof JLabel) {
                JLabel label = (JLabel) component;
                label.setOpaque(false);
                label.setBorder(BorderFactory.createEmptyBorder());
            }
        }
        focus.setOpaque(true);
        focus.setBorder(BorderFactory.createLineBorder(Color.black));
    }

    private File selectFile(FileFilter filter) {
        File fileReturn = null;
        faceTextureChooser.setFileFilter(filter);
        int returnVal = faceTextureChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File temp = faceTextureChooser.getSelectedFile();
            if (filter.accept(temp)) {
                fileReturn = temp;
            }
        }

        return fileReturn;
    }

    private void generateFaceTextureLabel() {
        facePanel.removeAll();
        faceTextureService.getFaceTextures().forEach(faceTexture -> {
            facePanel.add(faceTextureFromLabel(faceTexture, faceTextureService.getFaceTextures().indexOf(faceTexture)));
            facePanel.updateUI();
        });
    }

    private JLabel faceTextureFromLabel(FaceTexture faceTexture, int index) {
        JLabel label = new JLabel();
        label.setIcon(new ImageIcon(faceTexture.getImage(125, 160)));
        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                setIndexFaceTexture(evt, index);
            }
        });
        label.setBackground(Color.orange);
        return label;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> classComboBox;
    private javax.swing.JPanel facePanel;
    private javax.swing.JFileChooser faceTextureChooser;
    private javax.swing.JDialog faceTextureInternalFrame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelNewFaceTexture;
    private javax.swing.JLabel nameFaceTexture;
    private javax.swing.JCheckBox showClassCheckBox;
    // End of variables declaration//GEN-END:variables
}
