/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ItemEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.FaceTexture;
import service.BackgroundService;
import service.FaceTextureService;

/**
 *
 * @author ghpm9
 */
public class FaceTextureFrame extends javax.swing.JInternalFrame {

    private FaceTextureService faceTextureService;
    private BackgroundService backgroundService;
    private int indexFaceTexture = 0;

    /**
     * Creates new form FaceTextureFrame
     */
    public FaceTextureFrame(FaceTextureService faceTextureService, BackgroundService backgroundService) {
        this.faceTextureService = faceTextureService;
        this.backgroundService = backgroundService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        faceTextureChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        face1 = new javax.swing.JLabel();
        face2 = new javax.swing.JLabel();
        face3 = new javax.swing.JLabel();
        face4 = new javax.swing.JLabel();
        face5 = new javax.swing.JLabel();
        face6 = new javax.swing.JLabel();
        face7 = new javax.swing.JLabel();
        face8 = new javax.swing.JLabel();
        face9 = new javax.swing.JLabel();
        face10 = new javax.swing.JLabel();
        face11 = new javax.swing.JLabel();
        face12 = new javax.swing.JLabel();
        face13 = new javax.swing.JLabel();
        face14 = new javax.swing.JLabel();
        face15 = new javax.swing.JLabel();
        face16 = new javax.swing.JLabel();
        face17 = new javax.swing.JLabel();
        face18 = new javax.swing.JLabel();
        face19 = new javax.swing.JLabel();
        face20 = new javax.swing.JLabel();
        face21 = new javax.swing.JLabel();
        face22 = new javax.swing.JLabel();
        face23 = new javax.swing.JLabel();
        face24 = new javax.swing.JLabel();
        face25 = new javax.swing.JLabel();
        face26 = new javax.swing.JLabel();
        face27 = new javax.swing.JLabel();
        face28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        classComboBox = new javax.swing.JComboBox<>();
        showClassCheckBox = new javax.swing.JCheckBox();
        nameFaceTexture = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setTitle("FaceTexture");

        jPanel2.setLayout(new java.awt.GridLayout(4, 7, 5, 5));

        face1.setIcon(getIconFromFaceTexture(0));
        face1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face1MouseClicked(evt);
            }
        });
        jPanel2.add(face1);

        face2.setIcon(getIconFromFaceTexture(1));
        face2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face2MouseClicked(evt);
            }
        });
        jPanel2.add(face2);

        face3.setIcon(getIconFromFaceTexture(2));
        face3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face3MouseClicked(evt);
            }
        });
        jPanel2.add(face3);

        face4.setIcon(getIconFromFaceTexture(3));
        face4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face4MouseClicked(evt);
            }
        });
        jPanel2.add(face4);

        face5.setIcon(getIconFromFaceTexture(4));
        face5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face5MouseClicked(evt);
            }
        });
        jPanel2.add(face5);

        face6.setIcon(getIconFromFaceTexture(5));
        face6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face6MouseClicked(evt);
            }
        });
        jPanel2.add(face6);

        face7.setIcon(getIconFromFaceTexture(6));
        face7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face7MouseClicked(evt);
            }
        });
        jPanel2.add(face7);

        face8.setIcon(getIconFromFaceTexture(7));
        face8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face8MouseClicked(evt);
            }
        });
        jPanel2.add(face8);

        face9.setIcon(getIconFromFaceTexture(8));
        face9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face9MouseClicked(evt);
            }
        });
        jPanel2.add(face9);

        face10.setIcon(getIconFromFaceTexture(9));
        face10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face10MouseClicked(evt);
            }
        });
        jPanel2.add(face10);

        face11.setIcon(getIconFromFaceTexture(10));
        face11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face11MouseClicked(evt);
            }
        });
        jPanel2.add(face11);

        face12.setIcon(getIconFromFaceTexture(11));
        face12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face12MouseClicked(evt);
            }
        });
        jPanel2.add(face12);

        face13.setIcon(getIconFromFaceTexture(12));
        face13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face13MouseClicked(evt);
            }
        });
        jPanel2.add(face13);

        face14.setIcon(getIconFromFaceTexture(13));
        face14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face14MouseClicked(evt);
            }
        });
        jPanel2.add(face14);

        face15.setIcon(getIconFromFaceTexture(15));
        face15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face15MouseClicked(evt);
            }
        });
        jPanel2.add(face15);

        face16.setIcon(getIconFromFaceTexture(15));
        face16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face16MouseClicked(evt);
            }
        });
        jPanel2.add(face16);

        face17.setIcon(getIconFromFaceTexture(16));
        face17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face17MouseClicked(evt);
            }
        });
        jPanel2.add(face17);

        face18.setIcon(getIconFromFaceTexture(17));
        face18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face18MouseClicked(evt);
            }
        });
        jPanel2.add(face18);

        face19.setIcon(getIconFromFaceTexture(18));
        face19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face19MouseClicked(evt);
            }
        });
        jPanel2.add(face19);

        face20.setIcon(getIconFromFaceTexture(19));
        face20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face20MouseClicked(evt);
            }
        });
        jPanel2.add(face20);

        face21.setIcon(getIconFromFaceTexture(20));
        face21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face21MouseClicked(evt);
            }
        });
        jPanel2.add(face21);

        face22.setIcon(getIconFromFaceTexture(21));
        face22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face22MouseClicked(evt);
            }
        });
        jPanel2.add(face22);

        face23.setIcon(getIconFromFaceTexture(22));
        face23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face23MouseClicked(evt);
            }
        });
        jPanel2.add(face23);

        face24.setIcon(getIconFromFaceTexture(23));
        face24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face24MouseClicked(evt);
            }
        });
        jPanel2.add(face24);

        face25.setIcon(getIconFromFaceTexture(24));
        face25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face25MouseClicked(evt);
            }
        });
        jPanel2.add(face25);

        face26.setIcon(getIconFromFaceTexture(25));
        face26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face26MouseClicked(evt);
            }
        });
        jPanel2.add(face26);

        face27.setIcon(getIconFromFaceTexture(26));
        face27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face27MouseClicked(evt);
            }
        });
        jPanel2.add(face27);

        face28.setIcon(getIconFromFaceTexture(27));
        face28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face28MouseClicked(evt);
            }
        });
        jPanel2.add(face28);

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setMaximumSize(new java.awt.Dimension(930, 736));
        jPanel3.setMinimumSize(new java.awt.Dimension(930, 736));
        jPanel3.setOpaque(false);

        jLabel2.setText("Arquivo Nome");

        jLabel3.setText("Class:");

        classComboBox.setModel(getClassBDO());
        classComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                classComboBoxItemStateChanged(evt);
            }
        });

        showClassCheckBox.setText("Show Class");
        showClassCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showClassCheckBoxItemStateChanged(evt);
            }
        });

        nameFaceTexture.setText("name");

        jButton2.setText("Alterar Imagem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nameFaceTexture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(showClassCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 680, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameFaceTexture))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showClassCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void face1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face1MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 0);

    }//GEN-LAST:event_face1MouseClicked

    private void face2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face2MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 1);
    }//GEN-LAST:event_face2MouseClicked

    private void face3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face3MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 2);
    }//GEN-LAST:event_face3MouseClicked

    private void face4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face4MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 3);
    }//GEN-LAST:event_face4MouseClicked

    private void face5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face5MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 4);
    }//GEN-LAST:event_face5MouseClicked

    private void face6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face6MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 5);
    }//GEN-LAST:event_face6MouseClicked

    private void face7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face7MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 6);
    }//GEN-LAST:event_face7MouseClicked

    private void face8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face8MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 7);
    }//GEN-LAST:event_face8MouseClicked

    private void face9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face9MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 8);
    }//GEN-LAST:event_face9MouseClicked

    private void face10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face10MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 9);
    }//GEN-LAST:event_face10MouseClicked

    private void face11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face11MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 10);
    }//GEN-LAST:event_face11MouseClicked

    private void face12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face12MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 11);
    }//GEN-LAST:event_face12MouseClicked

    private void face13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face13MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 12);
    }//GEN-LAST:event_face13MouseClicked

    private void face14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face14MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 13);
    }//GEN-LAST:event_face14MouseClicked

    private void face15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face15MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 14);
    }//GEN-LAST:event_face15MouseClicked

    private void face16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face16MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 15);
    }//GEN-LAST:event_face16MouseClicked

    private void face17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face17MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 16);
    }//GEN-LAST:event_face17MouseClicked

    private void face18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face18MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 17);
    }//GEN-LAST:event_face18MouseClicked

    private void face19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face19MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 18);
    }//GEN-LAST:event_face19MouseClicked

    private void face20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face20MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 19);
    }//GEN-LAST:event_face20MouseClicked

    private void face21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face21MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 20);
    }//GEN-LAST:event_face21MouseClicked

    private void face22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face22MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 21);
    }//GEN-LAST:event_face22MouseClicked

    private void face23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face23MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 22);
    }//GEN-LAST:event_face23MouseClicked

    private void face24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face24MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 23);
    }//GEN-LAST:event_face24MouseClicked

    private void face25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face25MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 24);
    }//GEN-LAST:event_face25MouseClicked

    private void face26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face26MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 25);
    }//GEN-LAST:event_face26MouseClicked

    private void face27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face27MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 26);
    }//GEN-LAST:event_face27MouseClicked

    private void face28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face28MouseClicked
        // TODO add your handling code here:
        setIndexFaceTexture(evt, 27);
    }//GEN-LAST:event_face28MouseClicked

    private void showClassCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showClassCheckBoxItemStateChanged
        // TODO add your handling code here:
        faceTextureService.getFaceTexture(indexFaceTexture).setShowClasse(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_showClassCheckBoxItemStateChanged

    private void classComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_classComboBoxItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            faceTextureService.getFaceTexture(indexFaceTexture).setClasse((String) evt.getItem());
        }
    }//GEN-LAST:event_classComboBoxItemStateChanged

    private void updateChangeFaceTexture() {
        FaceTexture faceTextureTemp = faceTextureService.getFaceTexture(indexFaceTexture);
        nameFaceTexture.setText(faceTextureTemp.getName());
        classComboBox.setSelectedItem(faceTextureTemp.getClasse());
        showClassCheckBox.setSelected(faceTextureTemp.isShowClasse());
    }

    private Icon getIconFromFaceTexture(int index) {
        ImageIcon icon = new ImageIcon(faceTextureService.getFaceTexture(index).getImage(125,160));

        return icon;
    }

    private ComboBoxModel getClassBDO() {
        String[] vector = {
            "Warrior", "Ranger", "Sorceress", "Berserker", "Valkyrie", "Wizard", "Witch", "Tamer", "Maehwa", "Musa", "Ninja", "Kunoichi", "Dark Knight", "Striker", "Mystic", "Lahn", "Archer", "Shai", "Guardian", "Hashashin"
        };

        return new DefaultComboBoxModel(vector);
    }

    private void setIndexFaceTexture(MouseEvent event, int index) {
        this.indexFaceTexture = index;
        updateChangeFaceTexture();
        if (event.getClickCount() == 2 && event.getButton() == MouseEvent.BUTTON1) {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("BMP Images", "bmp");
            File file = selectFile(filter);
            if (file != null) {
                faceTextureService.getFaceTexture(indexFaceTexture).setName(file.getName());
                faceTextureService.getFaceTexture(indexFaceTexture).setImage(file.getAbsolutePath());
            }
            if (event.getComponent() instanceof JLabel) {
                ((JLabel) event.getComponent()).setIcon(getIconFromFaceTexture(indexFaceTexture));
            }
        }

    }

    private File selectFile(FileFilter filter) {
        File fileReturn = null;
        faceTextureChooser.setFileFilter(filter);
        int returnVal = faceTextureChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File temp = faceTextureChooser.getSelectedFile();
            if (filter.accept(temp)) {
                fileReturn = temp;
            }
        }

        return fileReturn;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> classComboBox;
    private javax.swing.JLabel face1;
    private javax.swing.JLabel face10;
    private javax.swing.JLabel face11;
    private javax.swing.JLabel face12;
    private javax.swing.JLabel face13;
    private javax.swing.JLabel face14;
    private javax.swing.JLabel face15;
    private javax.swing.JLabel face16;
    private javax.swing.JLabel face17;
    private javax.swing.JLabel face18;
    private javax.swing.JLabel face19;
    private javax.swing.JLabel face2;
    private javax.swing.JLabel face20;
    private javax.swing.JLabel face21;
    private javax.swing.JLabel face22;
    private javax.swing.JLabel face23;
    private javax.swing.JLabel face24;
    private javax.swing.JLabel face25;
    private javax.swing.JLabel face26;
    private javax.swing.JLabel face27;
    private javax.swing.JLabel face28;
    private javax.swing.JLabel face3;
    private javax.swing.JLabel face4;
    private javax.swing.JLabel face5;
    private javax.swing.JLabel face6;
    private javax.swing.JLabel face7;
    private javax.swing.JLabel face8;
    private javax.swing.JLabel face9;
    private javax.swing.JFileChooser faceTextureChooser;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameFaceTexture;
    private javax.swing.JCheckBox showClassCheckBox;
    // End of variables declaration//GEN-END:variables
}
