/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import service.BackgroundService;
import service.FaceTextureService;
import service.SaveService;

/**
 *
 * @author ghpm9
 */
public class MainFrame extends javax.swing.JFrame {

    private FaceTextureService faceTextureService;
    private BackgroundService backgroundService;
    private SaveService saveService;
    private final String version = "Versão 0.01B";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this.faceTextureService = new FaceTextureService();
        
        this.backgroundService = new BackgroundService("images/backgroundDefault.jpg",905,655);                
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        versionLabel = new javax.swing.JLabel();
        deskPanel = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        faceTextureMenuItem = new javax.swing.JMenuItem();
        exportMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        aboutDialog.setTitle("Sobre");
        aboutDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aboutDialog.setMinimumSize(new java.awt.Dimension(400, 300));
        aboutDialog.setModal(true);
        aboutDialog.setResizable(false);
        aboutDialog.setType(java.awt.Window.Type.POPUP);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Face Texture Editor");
        aboutDialog.getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Programado por Guilherme.\n\nKaworiChan#8102");
        jScrollPane1.setViewportView(jTextArea1);

        aboutDialog.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        versionLabel.setText("jLabel2");
        aboutDialog.getContentPane().add(versionLabel, java.awt.BorderLayout.PAGE_END);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Face Texture Editor");
        setExtendedState(MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(930, 736));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(deskPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Background");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        faceTextureMenuItem.setMnemonic('y');
        faceTextureMenuItem.setText("Face Textures");
        faceTextureMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faceTextureMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(faceTextureMenuItem);

        exportMenuItem.setMnemonic('p');
        exportMenuItem.setText("Exportar");
        exportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(exportMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void faceTextureMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faceTextureMenuItemActionPerformed
        
        FaceTextureFrame faceTextureFrame = new FaceTextureFrame(faceTextureService, backgroundService);

        faceTextureFrame.setClosable(true);
        faceTextureFrame.setIconifiable(false);
        faceTextureFrame.setResizable(true);

        deskPanel.add(faceTextureFrame);

        faceTextureFrame.setVisible(true);
        
        faceTextureFrame.addInternalFrameListener(getEventOnClosed());
    }//GEN-LAST:event_faceTextureMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        BackgroundFrame backgroundFrame = new BackgroundFrame(backgroundService);

        backgroundFrame.setClosable(true);
        backgroundFrame.setIconifiable(false);
        backgroundFrame.setResizable(true);

        deskPanel.add(backgroundFrame);

        backgroundFrame.setVisible(true);
        
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void exportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportMenuItemActionPerformed
        // TODO add your handling code here:
        ExportFrame exportFrame = new ExportFrame(backgroundService, faceTextureService);

        exportFrame.setClosable(true);
        exportFrame.setIconifiable(false);
        exportFrame.setResizable(true);

        deskPanel.add(exportFrame);

        exportFrame.setVisible(true);
    }//GEN-LAST:event_exportMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        versionLabel.setText(version);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private InternalFrameAdapter getEventOnClosed(){
        return new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e){
                saveService.save(faceTextureService.getFaceTextures());
            }
        };
    }
    
    private void load(){
        this.saveService = new SaveService();
        faceTextureService.setFaceTexture(saveService.load());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog aboutDialog;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane deskPanel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exportMenuItem;
    private javax.swing.JMenuItem faceTextureMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables

}
