/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import service.BackgroundService;
import service.FaceTextureService;

/**
 *
 * @author ghpm9
 */
public class MainFrame extends javax.swing.JFrame {

    private FaceTextureService faceTextureService;
    private BackgroundService backgroundService;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this.faceTextureService = new FaceTextureService();
        this.backgroundService = new BackgroundService();
        initComponents();

    }

    private ComboBoxModel getClassBDO() {
        String[] vector = {
            "Warrior", "Ranger", "Sorceress", "Berserker", "Valkyrie", "Wizard", "Witch", "Tamer", "Maehwa", "Musa", "Ninja", "Kunoichi", "Dark Knight", "Striker", "Mystic", "Lahn", "Archer", "Shai", "Guardian", "Hashashin"
        };
        
        return new DefaultComboBoxModel(vector);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        faceTextureChooser = new javax.swing.JFileChooser();
        deskPanel = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        faceTextureMenuItem = new javax.swing.JMenuItem();
        exportMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Face Texture Editor");
        setMinimumSize(new java.awt.Dimension(930, 736));
        getContentPane().add(deskPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        newMenuItem.setMnemonic('a');
        newMenuItem.setText("New");
        fileMenu.add(newMenuItem);

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Background");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        faceTextureMenuItem.setMnemonic('y');
        faceTextureMenuItem.setText("Face Textures");
        faceTextureMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faceTextureMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(faceTextureMenuItem);

        exportMenuItem.setMnemonic('p');
        exportMenuItem.setText("Exportar");
        exportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(exportMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void faceTextureMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faceTextureMenuItemActionPerformed
        // TODO add your handling code here:
//        int returnVal = faceTextureChooser.showOpenDialog(this);
//        if(returnVal == JFileChooser.APPROVE_OPTION){
//            File file = faceTextureChooser.getSelectedFile();
//            
//        }
          FaceTextureFrame faceTextureFrame = new FaceTextureFrame(faceTextureService, backgroundService);
          
          faceTextureFrame.setClosable(true);
          faceTextureFrame.setIconifiable(false);
          faceTextureFrame.setResizable(true);
          
          deskPanel.add(faceTextureFrame);
          
          faceTextureFrame.setVisible(true);
    }//GEN-LAST:event_faceTextureMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        BackgroundFrame backgroundFrame = new BackgroundFrame(backgroundService);
        
        backgroundFrame.setClosable(true);
        backgroundFrame.setIconifiable(false);
        backgroundFrame.setResizable(true);
        
        deskPanel.add(backgroundFrame);
        
        backgroundFrame.setVisible(true);
        
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void exportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane deskPanel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exportMenuItem;
    private javax.swing.JFileChooser faceTextureChooser;
    private javax.swing.JMenuItem faceTextureMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
